version: '3.1'
services:
  db:
    image: postgres:13.10-alpine3.17
    restart: always
    environment:
      POSTGRES_PASSWORD: fridayfinance
      POSTGRES_USER: fridayfinance
      POSTGRES_DB: fridayfinance
    ports:
      - 5432:5432
    volumes:
      - ./setup/init.sql:/docker-entrypoint-initdb.d/init.sql